apiVersion: v1
kind: Service
metadata:
  name: service-nodeapp
spec:
  selector:
      app: nodeapp
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
    nodePort: 31110